FROM python:3.11.7-slim

RUN pip install --no-cache-dir torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121

WORKDIR /app
COPY pyproject.toml poetry.lock ./

RUN pip install --timeout 600 --no-cache-dir poetry && \
    poetry config virtualenvs.create false && \
    poetry install --no-root --no-interaction --no-ansi
COPY . .
ENV PORT=8000
EXPOSE 8000
# Создайте скрипт запуска
CMD ["sh", "-c", "sleep 30 && uvicorn service:app --host 0.0.0.0 --port ${PORT} --reload"]